name: Push project on dockerhub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.20.6'

      - name: Publish Docker Image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: hwga
        run: |
          docker images
          docker build -t "${IMAGE_NAME}" .
          docker images
          echo "${PASSWORD}" | docker login --username "$USERNAME" --password-stdin
          docker tag "${IMAGE_NAME}" "${USERNAME}/${IMAGE_NAME}:latest"
          docker push "${USERNAME}/${IMAGE_NAME}:latest"
          echo "* Running Docker Image"
